  CREATE TABLE staff_master (
  id INT PRIMARY KEY IDENTITY,
  first_name VARCHAR(45) NULL,
  surname VARCHAR(45) NULL,
  email VARCHAR(45) NULL,
  insert_date DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  salary FLOAT NULL);